### ISSUE TITLE
0.1.0 (copper) release

### ISSUE THREAD

**Issue by gabro** [scalameta/metals#220]
This issue is to track the release of the 0.1.0 (codename nickel) release:

- [x] #218 Get the VSCode extension ready
- [x] #221 Report error for non-scala 2.12 project
- [x] #222 Move .compilerconfig to .metals/
- [x] #219 Publish sbt-metals plugin
- [x] #256 Document how to integrate with a new editor client
- [x] #257 Document how to integrate with a new build tool
- [x] #237 Update docs for 0.1.0
- ~~#239 Upgrade to Scalameta v3.7.0~~

**Comment by gabro** [comment]
We informally decided to cut a 0.1.0-M1 release once #219 is in

**Comment by gabro** [comment]
I agree 👍

**Comment by olafurpg** [comment]
I propose we cut a v0.1.0 with what we have in master right now, wdyt? The Scalameta v4 upgrade will wait for later since it is a big change.

**Comment by gabro** [comment]
Sounds good to me.

**Comment by olafurpg** [comment]
I just pushed the v0.1.0 tag. Will make sure the website is also published to Maven Central so the current state of this project is forever on Maven Central

**Comment by ivanopagano** [comment]
Do you plan to publish the code extension too in the marketplace?

**Comment by gabro** [comment]
I don't think so. The project status is highly unstable and it will radically change over the next few months. The fewer people use it now, the fast the project will move.

If you're curious enough, the website has fairly comprehensive docs on how to build the extension locally.

**Comment by gabro** [comment]
Well, 0.1.0 is out! 🎉
